/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, Timestamp, Uint64, ClaimEntry, QueryMsg, ClaimHistoryResponse, ClaimRecord, Coin, Addr, ConfigResponse, Config, DistributionResponse, Distribution, PendingClaimsResponse, PendingClaimInfo } from "./ClaimBase.types";
export interface ClaimBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  distribution: ({
    id
  }: {
    id: number;
  }) => Promise<DistributionResponse>;
  pendingClaims: ({
    user
  }: {
    user: string;
  }) => Promise<PendingClaimsResponse>;
  claimHistory: ({
    limit,
    startAfter,
    user
  }: {
    limit?: number;
    startAfter?: number;
    user: string;
  }) => Promise<ClaimHistoryResponse>;
}
export class ClaimBaseQueryClient implements ClaimBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.distribution = this.distribution.bind(this);
    this.pendingClaims = this.pendingClaims.bind(this);
    this.claimHistory = this.claimHistory.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  distribution = async ({
    id
  }: {
    id: number;
  }): Promise<DistributionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      distribution: {
        id
      }
    });
  };
  pendingClaims = async ({
    user
  }: {
    user: string;
  }): Promise<PendingClaimsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pending_claims: {
        user
      }
    });
  };
  claimHistory = async ({
    limit,
    startAfter,
    user
  }: {
    limit?: number;
    startAfter?: number;
    user: string;
  }): Promise<ClaimHistoryResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      claim_history: {
        limit,
        start_after: startAfter,
        user
      }
    });
  };
}
export interface ClaimBaseInterface extends ClaimBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createDistribution: ({
    claims,
    expiry
  }: {
    claims: ClaimEntry[];
    expiry: Timestamp;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claim: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  sweepExpired: ({
    distributionId
  }: {
    distributionId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    admin,
    treasury
  }: {
    admin?: string;
    treasury?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ClaimBaseClient extends ClaimBaseQueryClient implements ClaimBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createDistribution = this.createDistribution.bind(this);
    this.claim = this.claim.bind(this);
    this.sweepExpired = this.sweepExpired.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
  }
  createDistribution = async ({
    claims,
    expiry
  }: {
    claims: ClaimEntry[];
    expiry: Timestamp;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_distribution: {
        claims,
        expiry
      }
    }, fee, memo, _funds);
  };
  claim = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {}
    }, fee, memo, _funds);
  };
  sweepExpired = async ({
    distributionId
  }: {
    distributionId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      sweep_expired: {
        distribution_id: distributionId
      }
    }, fee, memo, _funds);
  };
  updateConfig = async ({
    admin,
    treasury
  }: {
    admin?: string;
    treasury?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        admin,
        treasury
      }
    }, fee, memo, _funds);
  };
}