/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin: string;
  treasury: string;
}
export type ExecuteMsg = {
  create_distribution: {
    claims: ClaimEntry[];
    expiry: Timestamp;
  };
} | {
  claim: {};
} | {
  sweep_expired: {
    distribution_id: number;
  };
} | {
  update_config: {
    admin?: string | null;
    treasury?: string | null;
  };
};
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface ClaimEntry {
  address: string;
  weight: Uint128;
}
export type QueryMsg = {
  config: {};
} | {
  distribution: {
    id: number;
  };
} | {
  pending_claims: {
    user: string;
  };
} | {
  claim_history: {
    limit?: number | null;
    start_after?: number | null;
    user: string;
  };
};
export interface ClaimHistoryResponse {
  claims: ClaimRecord[];
}
export interface ClaimRecord {
  claimed_at: Timestamp;
  distribution_id: number;
  funds_claimed: Coin[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  admin: Addr;
  treasury: Addr;
}
export interface DistributionResponse {
  distribution: Distribution;
}
export interface Distribution {
  expiry: Timestamp;
  id: number;
  original_funds: Coin[];
  remaining_funds: Coin[];
  total_weight: Uint128;
}
export interface PendingClaimsResponse {
  claims: PendingClaimInfo[];
}
export interface PendingClaimInfo {
  distribution_id: number;
  estimated_funds: Coin[];
  weight: Uint128;
}