/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  d_token_denom: string;
  drop_staking_core_contract: string;
  token_group_id: string;
}
export type ExecuteMsg = {
  update_token_ratio: {};
};
export type QueryMsg = {
  config: {};
} | {
  denom_info: {
    round_id: number;
  };
};
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  d_token_denom: string;
  drop_staking_core_contract: Addr;
  hydro_contract_address: Addr;
  token_group_id: string;
}
export type Decimal = string;
export interface DenomInfoResponse {
  denom: string;
  ratio: Decimal;
  token_group_id: string;
}