/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Addr, ConfigResponse, Config, ExecuteMsg, InstantiateMsg, QueryMsg } from "./FundCalculationBase.types";
export interface FundCalculationBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
}
export class FundCalculationBaseQueryClient implements FundCalculationBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
}