/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  hydro_contract: Addr;
}
export type ExecuteMsg = string;
export interface InstantiateMsg {
  hydro_contract: string;
}
export type QueryMsg = {
  config: {};
};