/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
}
export type ExecuteMsg = {
  register_stage: {
    activate_at: Timestamp;
    hrp?: string | null;
    merkle_root: string;
    start_new_epoch: boolean;
  };
} | {
  lock_tokens: ExecuteLockTokensMsg;
} | {
  add_admin: {
    admin: string;
  };
} | {
  remove_admin: {
    admin: string;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export type Binary = string;
export interface ExecuteLockTokensMsg {
  amount_to_lock: Uint128;
  maximum_amount: Uint128;
  proof: string[];
  sig_info?: SignatureInfo | null;
  user_address: string;
}
export interface SignatureInfo {
  claim_msg: Binary;
  signature: Binary;
}
export type QueryMsg = {
  config: {};
} | {
  current_stage: {};
} | {
  admins: {};
} | {
  current_epoch_user_locked: {
    user_address: string;
  };
};
export type Addr = string;
export interface AdminsResponse {
  admins: Addr[];
}
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  hydro_contract: Addr;
}
export interface CurrentEpochUserLockedResponse {
  currently_locked: Uint128;
}
export interface CurrentStageResponse {
  stage: StageData;
}
export interface StageData {
  activate_at: Timestamp;
  hrp?: string | null;
  merkle_root: string;
  stage_id: number;
}