/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type Addr = string;
export interface AllUserLockupsResponse {
  lockups: LockEntryWithPower[];
}
export interface LockEntryWithPower {
  current_voting_power: Uint128;
  lock_entry: LockEntryV2;
}
export interface LockEntryV2 {
  funds: Coin;
  lock_end: Timestamp;
  lock_id: number;
  lock_start: Timestamp;
  owner: Addr;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface AllUserLockupsWithTrancheInfosResponse {
  lockups_with_per_tranche_infos: LockupWithPerTrancheInfo[];
}
export interface LockupWithPerTrancheInfo {
  lock_with_power: LockEntryWithPower;
  per_tranche_info: PerTrancheLockupInfo[];
}
export interface PerTrancheLockupInfo {
  current_voted_on_proposal?: number | null;
  next_round_lockup_can_vote: number;
  tied_to_proposal?: number | null;
  tranche_id: number;
}
export type Decimal = string;
export interface AllVotesResponse {
  votes: VoteEntry[];
}
export interface VoteEntry {
  lock_id: number;
  round_id: number;
  sender_addr: Addr;
  tranche_id: number;
  vote: Vote;
}
export interface Vote {
  prop_id: number;
  time_weighted_shares: [string, Decimal];
}
export interface AllVotesRoundTrancheResponse {
  votes: VoteEntry[];
}
export interface CanLockDenomResponse {
  can_be_locked: boolean;
  denom: string;
}
export interface ConstantsResponse {
  constants: Constants;
}
export interface Constants {
  first_round_start: Timestamp;
  known_users_cap: number;
  lock_epoch_length: number;
  max_deployment_duration: number;
  max_locked_tokens: number;
  paused: boolean;
  round_length: number;
  round_lock_power_schedule: RoundLockPowerSchedule;
}
export interface RoundLockPowerSchedule {
  round_lock_power_schedule: LockPowerEntry[];
}
export interface LockPowerEntry {
  locked_rounds: number;
  power_scaling_factor: Decimal;
}
export interface CurrentRoundResponse {
  round_end: Timestamp;
  round_id: number;
}
export type ExecuteMsg = {
  lock_tokens: {
    lock_duration: number;
  };
} | {
  refresh_lock_duration: {
    lock_duration: number;
    lock_ids: number[];
  };
} | {
  unlock_tokens: {
    lock_ids?: number[] | null;
  };
} | {
  create_proposal: {
    deployment_duration: number;
    description: string;
    minimum_atom_liquidity_request: Uint128;
    round_id?: number | null;
    title: string;
    tranche_id: number;
  };
} | {
  vote: {
    proposals_votes: ProposalToLockups[];
    tranche_id: number;
  };
} | {
  unvote: {
    lock_ids: number[];
    tranche_id: number;
  };
} | {
  add_account_to_whitelist: {
    address: string;
  };
} | {
  remove_account_from_whitelist: {
    address: string;
  };
} | {
  update_config: {
    activate_at: Timestamp;
    known_users_cap?: number | null;
    max_deployment_duration?: number | null;
    max_locked_tokens?: number | null;
  };
} | {
  delete_configs: {
    timestamps: Timestamp[];
  };
} | {
  pause: {};
} | {
  add_tranche: {
    tranche: TrancheInfo;
  };
} | {
  edit_tranche: {
    tranche_id: number;
    tranche_metadata?: string | null;
    tranche_name?: string | null;
  };
} | {
  create_icqs_for_validators: {
    validators: string[];
  };
} | {
  add_i_c_q_manager: {
    address: string;
  };
} | {
  remove_i_c_q_manager: {
    address: string;
  };
} | {
  withdraw_i_c_q_funds: {
    amount: Uint128;
  };
} | {
  add_liquidity_deployment: {
    deployed_funds: Coin[];
    destinations: string[];
    funds_before_deployment: Coin[];
    proposal_id: number;
    remaining_rounds: number;
    round_id: number;
    total_rounds: number;
    tranche_id: number;
  };
} | {
  remove_liquidity_deployment: {
    proposal_id: number;
    round_id: number;
    tranche_id: number;
  };
} | {
  update_token_group_ratio: {
    new_ratio: Decimal;
    old_ratio: Decimal;
    token_group_id: string;
  };
} | {
  add_token_info_provider: {
    token_info_provider: TokenInfoProviderInstantiateMsg;
  };
} | {
  remove_token_info_provider: {
    provider_id: string;
  };
};
export type TokenInfoProviderInstantiateMsg = {
  lsm: {
    hub_connection_id: string;
    hub_transfer_channel_id: string;
    icq_update_period: number;
    max_validator_shares_participating: number;
  };
} | {
  token_info_provider_contract: {
    admin?: string | null;
    code_id: number;
    label: string;
    msg: Binary;
  };
};
export type Binary = string;
export interface ProposalToLockups {
  lock_ids: number[];
  proposal_id: number;
}
export interface TrancheInfo {
  metadata: string;
  name: string;
}
export interface ExpiredUserLockupsResponse {
  lockups: LockEntryV2[];
}
export interface ICQManagersResponse {
  managers: Addr[];
}
export interface InstantiateMsg {
  first_round_start: Timestamp;
  icq_managers: string[];
  initial_whitelist: string[];
  lock_epoch_length: number;
  max_deployment_duration: number;
  max_locked_tokens: Uint128;
  round_length: number;
  round_lock_power_schedule: [number, Decimal][];
  token_info_providers: TokenInfoProviderInstantiateMsg[];
  tranches: TrancheInfo[];
  whitelist_admins: string[];
}
export interface LiquidityDeploymentResponse {
  liquidity_deployment: LiquidityDeployment;
}
export interface LiquidityDeployment {
  deployed_funds: Coin[];
  destinations: string[];
  funds_before_deployment: Coin[];
  proposal_id: number;
  remaining_rounds: number;
  round_id: number;
  total_rounds: number;
  tranche_id: number;
}
export interface ProposalResponse {
  proposal: Proposal;
}
export interface Proposal {
  deployment_duration: number;
  description: string;
  minimum_atom_liquidity_request: Uint128;
  percentage: Uint128;
  power: Uint128;
  proposal_id: number;
  round_id: number;
  title: string;
  tranche_id: number;
}
export type QueryMsg = {
  constants: {};
} | {
  token_info_providers: {};
} | {
  tranches: {};
} | {
  all_user_lockups: {
    address: string;
    limit: number;
    start_from: number;
  };
} | {
  specific_user_lockups: {
    address: string;
    lock_ids: number[];
  };
} | {
  all_user_lockups_with_tranche_infos: {
    address: string;
    limit: number;
    start_from: number;
  };
} | {
  specific_user_lockups_with_tranche_infos: {
    address: string;
    lock_ids: number[];
  };
} | {
  expired_user_lockups: {
    address: string;
    limit: number;
    start_from: number;
  };
} | {
  user_voting_power: {
    address: string;
  };
} | {
  user_votes: {
    address: string;
    round_id: number;
    tranche_id: number;
  };
} | {
  user_voted_locks: {
    address: string;
    round_id: number;
    tranche_id: number;
  };
} | {
  all_votes: {
    limit: number;
    start_from: number;
  };
} | {
  all_votes_round_tranche: {
    limit: number;
    round_id: number;
    start_from: number;
    tranche_id: number;
  };
} | {
  current_round: {};
} | {
  round_end: {
    round_id: number;
  };
} | {
  round_total_voting_power: {
    round_id: number;
  };
} | {
  round_proposals: {
    limit: number;
    round_id: number;
    start_from: number;
    tranche_id: number;
  };
} | {
  proposal: {
    proposal_id: number;
    round_id: number;
    tranche_id: number;
  };
} | {
  top_n_proposals: {
    number_of_proposals: number;
    round_id: number;
    tranche_id: number;
  };
} | {
  whitelist: {};
} | {
  whitelist_admins: {};
} | {
  i_c_q_managers: {};
} | {
  total_locked_tokens: {};
} | {
  registered_validator_queries: {};
} | {
  can_lock_denom: {
    token_denom: string;
  };
} | {
  liquidity_deployment: {
    proposal_id: number;
    round_id: number;
    tranche_id: number;
  };
} | {
  round_tranche_liquidity_deployments: {
    limit: number;
    round_id: number;
    start_from: number;
    tranche_id: number;
  };
} | {
  total_power_at_height: {
    height?: number | null;
  };
} | {
  voting_power_at_height: {
    address: string;
    height?: number | null;
  };
};
export interface RegisteredValidatorQueriesResponse {
  query_ids: [string, number][];
}
export interface RoundEndResponse {
  round_end: Timestamp;
}
export interface RoundProposalsResponse {
  proposals: Proposal[];
}
export interface RoundTotalVotingPowerResponse {
  total_voting_power: Uint128;
}
export interface RoundTrancheLiquidityDeploymentsResponse {
  liquidity_deployments: LiquidityDeployment[];
}
export interface SpecificUserLockupsResponse {
  lockups: LockEntryWithPower[];
}
export interface SpecificUserLockupsWithTrancheInfosResponse {
  lockups_with_per_tranche_infos: LockupWithPerTrancheInfo[];
}
export type TokenInfoProvider = {
  lsm: TokenInfoProviderLSM;
} | {
  derivative: TokenInfoProviderDerivative;
};
export interface TokenInfoProvidersResponse {
  providers: TokenInfoProvider[];
}
export interface TokenInfoProviderLSM {
  hub_connection_id: string;
  hub_transfer_channel_id: string;
  icq_update_period: number;
  max_validator_shares_participating: number;
}
export interface TokenInfoProviderDerivative {
  cache: {};
  contract: string;
}
export interface TopNProposalsResponse {
  proposals: Proposal[];
}
export interface TotalLockedTokensResponse {
  total_locked_tokens: number;
}
export interface TotalPowerAtHeightResponse {
  height: number;
  power: Uint128;
}
export interface TranchesResponse {
  tranches: Tranche[];
}
export interface Tranche {
  id: number;
  metadata: string;
  name: string;
}
export interface UserVotedLocksResponse {
  voted_locks: [number, VotedLockInfo[]][];
}
export interface VotedLockInfo {
  lock_id: number;
  power: Decimal;
}
export interface UserVotesResponse {
  votes: VoteWithPower[];
}
export interface VoteWithPower {
  power: Decimal;
  prop_id: number;
}
export interface UserVotingPowerResponse {
  voting_power: number;
}
export interface VotingPowerAtHeightResponse {
  height: number;
  power: Uint128;
}
export interface WhitelistAdminsResponse {
  admins: Addr[];
}
export interface WhitelistResponse {
  whitelist: Addr[];
}