/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export type SwapVenue = "neutron_astroport" | "osmosis";
export interface InstantiateMsg {
  admins: string[];
  default_timeout_nanos: number;
  executors: string[];
  ibc_adapter: string;
  initial_depositors: string[];
  initial_routes: [string, UnifiedRoute][];
  max_slippage_bps: number;
  skip_contracts: {};
}
export interface UnifiedRoute {
  denom_in: string;
  denom_out: string;
  enabled: boolean;
  forward_path: PathHop[];
  operations: SwapOperation[];
  recover_address?: string | null;
  return_path: PathHop[];
  swap_venue_name: string;
  venue: SwapVenue;
}
export interface PathHop {
  chain_id: string;
  channel: string;
  receiver: string;
}
export interface SwapOperation {
  denom_in: string;
  denom_out: string;
  interface?: Binary | null;
  pool: string;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: SkipAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
};
export type Uint128 = string;
export type SkipAdapterMsg = {
  execute_swap: {
    params: SwapParams;
  };
} | {
  register_route: {
    route: UnifiedRoute;
    route_id: string;
  };
} | {
  unregister_route: {
    route_id: string;
  };
} | {
  set_route_enabled: {
    enabled: boolean;
    route_id: string;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  update_config: {
    default_timeout_nanos?: number | null;
    ibc_adapter?: string | null;
    max_slippage_bps?: number | null;
    skip_contracts?: {} | null;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface SwapParams {
  amount_in: Uint128;
  min_amount_out: Uint128;
  route_id: string;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: SkipAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export type SkipAdapterQueryMsg = {
  route: {
    route_id: string;
  };
} | {
  all_routes: {
    venue?: SwapVenue | null;
  };
} | {
  executors: {};
};