/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  deposit_cap: Uint128;
  fee_config?: FeeConfigInit | null;
  subvaults: string[];
  whitelist: string[];
}
export interface FeeConfigInit {
  fee_rate: Decimal;
  fee_recipient: string;
}
export type ExecuteMsg = {
  submit_deployed_amount: {
    amount: Uint128;
  };
} | {
  update_deployed_amount: {
    amount: Uint128;
    direction: DeploymentDirection;
  };
} | {
  add_to_whitelist: {
    address: string;
  };
} | {
  remove_from_whitelist: {
    address: string;
  };
} | {
  update_config: {
    config: UpdateConfigData;
  };
} | {
  add_subvault: {
    address: string;
  };
} | {
  remove_subvault: {
    address: string;
  };
} | {
  accrue_fees: {};
} | {
  update_fee_config: {
    fee_rate?: Decimal | null;
    fee_recipient?: string | null;
  };
};
export type DeploymentDirection = "add" | "subtract";
export interface UpdateConfigData {
  deposit_cap?: Uint128 | null;
}
export type QueryMsg = {
  config: {};
} | {
  deployed_amount: {};
} | {
  pool_info: {};
} | {
  whitelist: {};
} | {
  subvaults: {};
} | {
  fee_config: {};
} | {
  fee_accrual_info: {};
};
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  deposit_cap: Uint128;
}
export interface FeeAccrualInfoResponse {
  current_share_price: Decimal;
  high_water_mark_price: Decimal;
  pending_fee: Uint128;
  pending_yield: Uint128;
}
export type Addr = string;
export interface FeeConfigResponse {
  fee_rate: Decimal;
  fee_recipient: Addr;
}
export interface PoolInfoResponse {
  total_pool_value: Uint128;
  total_shares_issued: Uint128;
}
export interface SubvaultsResponse {
  subvaults: Addr[];
}
export interface WhitelistResponse {
  whitelist: Addr[];
}