/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, RecipientConfig, RouteConfig, ExecuteMsg, AdapterInterfaceMsg, Uint128, Binary, SkipAdapterMsg, Asset, PostSwapAction, Coin, SwapExecutionParams, SwapOperation, QueryMsg, AdapterInterfaceQueryMsg, SkipAdapterQueryMsg } from "./InflowSkipAdapterBase.types";
export interface InflowSkipAdapterBaseReadOnlyInterface {
  contractAddress: string;
  standardQuery: (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg) => Promise<Binary>;
  customQuery: (skipAdapterQueryMsg: SkipAdapterQueryMsg) => Promise<Binary>;
}
export class InflowSkipAdapterBaseQueryClient implements InflowSkipAdapterBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.standardQuery = this.standardQuery.bind(this);
    this.customQuery = this.customQuery.bind(this);
  }
  standardQuery = async (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      standard_query: adapterInterfaceQueryMsg
    });
  };
  customQuery = async (skipAdapterQueryMsg: SkipAdapterQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      custom_query: skipAdapterQueryMsg
    });
  };
}
export interface InflowSkipAdapterBaseInterface extends InflowSkipAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  standardAction: (adapterInterfaceMsg: AdapterInterfaceMsg, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  customAction: (skipAdapterMsg: SkipAdapterMsg, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowSkipAdapterBaseClient extends InflowSkipAdapterBaseQueryClient implements InflowSkipAdapterBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.standardAction = this.standardAction.bind(this);
    this.customAction = this.customAction.bind(this);
  }
  standardAction = async (adapterInterfaceMsg: AdapterInterfaceMsg, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      standard_action: adapterInterfaceMsg
    }, fee_, memo_, funds_);
  };
  customAction = async (skipAdapterMsg: SkipAdapterMsg, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      custom_action: skipAdapterMsg
    }, fee_, memo_, funds_);
  };
}