/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  depositor_address?: string | null;
  mars_credit_manager: string;
  mars_params: string;
  mars_red_bank: string;
  supported_denoms: string[];
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: MarsAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
};
export type Uint128 = string;
export type Binary = string;
export type MarsAdapterMsg = {
  update_config: {
    mars_credit_manager?: string | null;
    mars_params?: string | null;
    mars_red_bank?: string | null;
    supported_denoms?: string[] | null;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: MarsAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export type MarsAdapterQueryMsg = string;