/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Binary, SwapVenue, InstantiateMsg, UnifiedRoute, SwapOperation, ReturnHop, ExecuteMsg, AdapterInterfaceMsg, Uint128, SkipAdapterMsg, Coin, SwapParams, QueryMsg, AdapterInterfaceQueryMsg, SkipAdapterQueryMsg } from "./InflowSkipAdapterBase.types";
export interface InflowSkipAdapterBaseReadOnlyInterface {
  contractAddress: string;
  standardQuery: (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg) => Promise<Binary>;
  customQuery: (skipAdapterQueryMsg: SkipAdapterQueryMsg) => Promise<Binary>;
}
export class InflowSkipAdapterBaseQueryClient implements InflowSkipAdapterBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.standardQuery = this.standardQuery.bind(this);
    this.customQuery = this.customQuery.bind(this);
  }
  standardQuery = async (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      standard_query: adapterInterfaceQueryMsg
    });
  };
  customQuery = async (skipAdapterQueryMsg: SkipAdapterQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      custom_query: skipAdapterQueryMsg
    });
  };
}
export interface InflowSkipAdapterBaseInterface extends InflowSkipAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  standardAction: (adapterInterfaceMsg: AdapterInterfaceMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  customAction: (skipAdapterMsg: SkipAdapterMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class InflowSkipAdapterBaseClient extends InflowSkipAdapterBaseQueryClient implements InflowSkipAdapterBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.standardAction = this.standardAction.bind(this);
    this.customAction = this.customAction.bind(this);
  }
  standardAction = async (adapterInterfaceMsg: AdapterInterfaceMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      standard_action: adapterInterfaceMsg
    }, fee, memo, _funds);
  };
  customAction = async (skipAdapterMsg: SkipAdapterMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      custom_action: skipAdapterMsg
    }, fee, memo, _funds);
  };
}