/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
}
export type ExecuteMsg = {
  forward_to_inflow: {};
} | {
  withdraw_receipt_tokens: {
    address: string;
    amount: Uint128;
  };
} | {
  withdraw_funds: {
    address: string;
    amount: Uint128;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  state: {};
};
export type Addr = string;
export type ActionState = ("idle" | "forwarded") | {
  withdraw_receipt_tokens: {
    amount: Uint128;
    recipient: Addr;
  };
} | {
  withdraw_funds: {
    amount: Uint128;
    recipient: Addr;
  };
};
export interface StateResponse {
  state: State;
}
export interface State {
  admins: Addr[];
  last_action: ActionState;
}