/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, ProxyAddressResponse } from "./InflowUserRegistryBase.types";
export interface InflowUserRegistryBaseReadOnlyInterface {
  contractAddress: string;
  proxyAddress: ({
    userId
  }: {
    userId: string;
  }) => Promise<ProxyAddressResponse>;
}
export class InflowUserRegistryBaseQueryClient implements InflowUserRegistryBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.proxyAddress = this.proxyAddress.bind(this);
  }
  proxyAddress = async ({
    userId
  }: {
    userId: string;
  }): Promise<ProxyAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      proxy_address: {
        user_id: userId
      }
    });
  };
}
export interface InflowUserRegistryBaseInterface extends InflowUserRegistryBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  registerUser: ({
    proxyAddress,
    userId
  }: {
    proxyAddress: string;
    userId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class InflowUserRegistryBaseClient extends InflowUserRegistryBaseQueryClient implements InflowUserRegistryBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.registerUser = this.registerUser.bind(this);
  }
  registerUser = async ({
    proxyAddress,
    userId
  }: {
    proxyAddress: string;
    userId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_user: {
        proxy_address: proxyAddress,
        user_id: userId
      }
    }, fee, memo, _funds);
  };
}