/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, Coin, QueryMsg, AllPositionsResponse, AvailableAmountResponse, AdapterConfigResponse, DepositorPositionResponse, DepositorPositionsResponse, RegisteredDepositorsResponse, RegisteredDepositorInfo, TimeEstimateResponse } from "./InflowMarsAdapterBase.types";
export interface InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  availableForDeposit: ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }) => Promise<AvailableAmountResponse>;
  availableForWithdraw: ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }) => Promise<AvailableAmountResponse>;
  timeToWithdraw: ({
    coin,
    depositorAddress
  }: {
    coin: Coin;
    depositorAddress: string;
  }) => Promise<TimeEstimateResponse>;
  config: () => Promise<AdapterConfigResponse>;
  allPositions: () => Promise<AllPositionsResponse>;
  registeredDepositors: ({
    enabled
  }: {
    enabled?: boolean;
  }) => Promise<RegisteredDepositorsResponse>;
  depositorPosition: ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }) => Promise<DepositorPositionResponse>;
  depositorPositions: ({
    depositorAddress
  }: {
    depositorAddress: string;
  }) => Promise<DepositorPositionsResponse>;
}
export class InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.availableForDeposit = this.availableForDeposit.bind(this);
    this.availableForWithdraw = this.availableForWithdraw.bind(this);
    this.timeToWithdraw = this.timeToWithdraw.bind(this);
    this.config = this.config.bind(this);
    this.allPositions = this.allPositions.bind(this);
    this.registeredDepositors = this.registeredDepositors.bind(this);
    this.depositorPosition = this.depositorPosition.bind(this);
    this.depositorPositions = this.depositorPositions.bind(this);
  }
  availableForDeposit = async ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }): Promise<AvailableAmountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_for_deposit: {
        denom,
        depositor_address: depositorAddress
      }
    });
  };
  availableForWithdraw = async ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }): Promise<AvailableAmountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_for_withdraw: {
        denom,
        depositor_address: depositorAddress
      }
    });
  };
  timeToWithdraw = async ({
    coin,
    depositorAddress
  }: {
    coin: Coin;
    depositorAddress: string;
  }): Promise<TimeEstimateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      time_to_withdraw: {
        coin,
        depositor_address: depositorAddress
      }
    });
  };
  config = async (): Promise<AdapterConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  allPositions = async (): Promise<AllPositionsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_positions: {}
    });
  };
  registeredDepositors = async ({
    enabled
  }: {
    enabled?: boolean;
  }): Promise<RegisteredDepositorsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      registered_depositors: {
        enabled
      }
    });
  };
  depositorPosition = async ({
    denom,
    depositorAddress
  }: {
    denom: string;
    depositorAddress: string;
  }): Promise<DepositorPositionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      depositor_position: {
        denom,
        depositor_address: depositorAddress
      }
    });
  };
  depositorPositions = async ({
    depositorAddress
  }: {
    depositorAddress: string;
  }): Promise<DepositorPositionsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      depositor_positions: {
        depositor_address: depositorAddress
      }
    });
  };
}
export interface InflowMarsAdapterBaseInterface extends InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  deposit: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdraw: ({
    coin
  }: {
    coin: Coin;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerDepositor: ({
    depositorAddress
  }: {
    depositorAddress: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  unregisterDepositor: ({
    depositorAddress
  }: {
    depositorAddress: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  toggleDepositorEnabled: ({
    depositorAddress,
    enabled
  }: {
    depositorAddress: string;
    enabled: boolean;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    protocolAddress,
    supportedDenoms
  }: {
    protocolAddress?: string;
    supportedDenoms?: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowMarsAdapterBaseClient extends InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.registerDepositor = this.registerDepositor.bind(this);
    this.unregisterDepositor = this.unregisterDepositor.bind(this);
    this.toggleDepositorEnabled = this.toggleDepositorEnabled.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
  }
  deposit = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit: {}
    }, fee_, memo_, funds_);
  };
  withdraw = async ({
    coin
  }: {
    coin: Coin;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        coin
      }
    }, fee_, memo_, funds_);
  };
  registerDepositor = async ({
    depositorAddress
  }: {
    depositorAddress: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_depositor: {
        depositor_address: depositorAddress
      }
    }, fee_, memo_, funds_);
  };
  unregisterDepositor = async ({
    depositorAddress
  }: {
    depositorAddress: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unregister_depositor: {
        depositor_address: depositorAddress
      }
    }, fee_, memo_, funds_);
  };
  toggleDepositorEnabled = async ({
    depositorAddress,
    enabled
  }: {
    depositorAddress: string;
    enabled: boolean;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      toggle_depositor_enabled: {
        depositor_address: depositorAddress,
        enabled
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    protocolAddress,
    supportedDenoms
  }: {
    protocolAddress?: string;
    supportedDenoms?: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        protocol_address: protocolAddress,
        supported_denoms: supportedDenoms
      }
    }, fee_, memo_, funds_);
  };
}