/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  eureka_fee_receiver: string;
  eureka_fee_timeout_seconds: number;
  ibc_transfer_timeout_seconds: number;
  initial_allowed_destination_addresses: string[];
  initial_denoms: string[];
  initial_depositors: InitialDepositor[];
  initial_executors: InitialExecutor[];
  skip_swap_entry_point_contract: string;
  source_channel: string;
}
export interface InitialDepositor {
  address: string;
  capabilities?: DepositorCapabilities | null;
}
export interface DepositorCapabilities {
  can_withdraw: boolean;
}
export interface InitialExecutor {
  address: string;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: IbcEurekaAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
} | {
  add_admin: {
    admin_address: string;
  };
} | {
  remove_admin: {
    admin_address: string;
  };
};
export type Uint128 = string;
export type Binary = string;
export type IbcEurekaAdapterMsg = {
  update_config: {
    update: UpdateConfigData;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  add_allowed_denom: {
    denom: string;
  };
} | {
  remove_allowed_denom: {
    denom: string;
  };
} | {
  add_allowed_destination_address: {
    address: string;
  };
} | {
  remove_allowed_destination_address: {
    address: string;
  };
} | {
  transfer_funds: {
    amount: Uint128;
    denom: string;
    recipient: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface UpdateConfigData {
  encoding?: string | null;
  eureka_fee_receiver?: string | null;
  eureka_fee_timeout_seconds?: number | null;
  ibc_transfer_timeout_seconds?: number | null;
  skip_swap_entry_point_contract?: string | null;
  source_channel?: string | null;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: IbcEurekaAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
} | {
  admins: {};
};
export type IbcEurekaAdapterQueryMsg = {
  allowed_denoms: {};
} | {
  executors: {};
} | {
  depositor_capabilities: {
    depositor_address: string;
  };
} | {
  allowed_destination_addresses: {
    limit?: number | null;
    start_after?: string | null;
  };
};