/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  depositor_address?: string | null;
  mars_contract: string;
  supported_denoms: string[];
}
export type ExecuteMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  toggle_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
} | {
  update_config: {
    protocol_address?: string | null;
    supported_denoms?: string[] | null;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type QueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  total_deposited: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export interface AvailableAmountResponse {
  amount: Uint128;
}
export interface AdapterConfigResponse {
  protocol_address: string;
  supported_denoms: string[];
}
export interface DepositorPositionResponse {
  amount: Uint128;
}
export interface DepositorPositionsResponse {
  positions: Coin[];
}
export interface RegisteredDepositorsResponse {
  depositors: RegisteredDepositorInfo[];
}
export interface RegisteredDepositorInfo {
  depositor_address: string;
  enabled: boolean;
}
export interface TimeEstimateResponse {
  blocks: number;
  seconds: number;
}
export interface TotalDepositedResponse {
  positions: Coin[];
}