/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  control_centers: string[];
}
export type ExecuteMsg = {
  forward_to_inflow: {};
} | {
  withdraw_receipt_tokens: {
    address: string;
    coin: Coin;
  };
} | {
  withdraw_funds: {
    address: string;
    coin: Coin;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type QueryMsg = {
  config: {};
} | {
  state: {};
};
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  admins: Addr[];
  control_centers: Addr[];
}
export type ActionState = ("idle" | "forwarded") | {
  withdraw_receipt_tokens: {
    coin: Coin;
    recipient: Addr;
  };
} | {
  withdraw_funds: {
    coin: Coin;
    recipient: Addr;
  };
};
export interface StateResponse {
  state: State;
}
export interface State {
  last_action: ActionState;
}