/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  control_center_contract: string;
  deposit_denom: string;
  max_withdrawals_per_user: number;
  subdenom: string;
  token_info_provider_contract?: string | null;
  token_metadata: DenomMetadata;
  whitelist: string[];
}
export interface DenomMetadata {
  description: string;
  display: string;
  exponent: number;
  name: string;
  symbol: string;
  uri?: string | null;
  uri_hash?: string | null;
}
export type ExecuteMsg = {
  deposit: {
    on_behalf_of?: string | null;
  };
} | {
  withdraw: {
    on_behalf_of?: string | null;
  };
} | {
  cancel_withdrawal: {
    withdrawal_ids: number[];
  };
} | {
  fulfill_pending_withdrawals: {
    limit: number;
  };
} | {
  claim_unbonded_withdrawals: {
    withdrawal_ids: number[];
  };
} | {
  withdraw_for_deployment: {
    amount: Uint128;
  };
} | {
  set_token_info_provider_contract: {
    address?: string | null;
  };
} | {
  add_to_whitelist: {
    address: string;
  };
} | {
  remove_from_whitelist: {
    address: string;
  };
} | {
  update_config: {
    config: UpdateConfigData;
  };
} | {
  register_adapter: {
    address: string;
    allocation_mode: AllocationMode;
    deployment_tracking: DeploymentTracking;
    description?: string | null;
    name: string;
  };
} | {
  unregister_adapter: {
    name: string;
  };
} | {
  set_adapter_allocation_mode: {
    allocation_mode: AllocationMode;
    name: string;
  };
} | {
  set_adapter_deployment_tracking: {
    deployment_tracking: DeploymentTracking;
    name: string;
  };
} | {
  withdraw_from_adapter: {
    adapter_name: string;
    amount: Uint128;
  };
} | {
  deposit_to_adapter: {
    adapter_name: string;
    amount: Uint128;
  };
};
export type Uint128 = string;
export type AllocationMode = "automated" | "manual";
export type DeploymentTracking = "tracked" | "not_tracked";
export interface UpdateConfigData {
  max_withdrawals_per_user?: number | null;
}
export type QueryMsg = {
  config: {};
} | {
  pool_info: {};
} | {
  shares_equivalent_value: {
    shares: Uint128;
  };
} | {
  user_shares_equivalent_value: {
    address: string;
  };
} | {
  available_for_deployment: {};
} | {
  withdrawal_queue_info: {};
} | {
  amount_to_fund_pending_withdrawals: {};
} | {
  funded_withdrawal_requests: {
    limit: number;
  };
} | {
  user_withdrawal_requests: {
    address: string;
    limit: number;
    start_from: number;
  };
} | {
  user_payouts_history: {
    address: string;
    limit: number;
    order: Order;
    start_from: number;
  };
} | {
  whitelist: {};
} | {
  list_adapters: {};
} | {
  adapter_info: {
    name: string;
  };
};
export type Order = "ascending" | "descending";
export type Addr = string;
export interface AdapterInfoResponse {
  info: AdapterInfo;
}
export interface AdapterInfo {
  address: Addr;
  allocation_mode: AllocationMode;
  deployment_tracking: DeploymentTracking;
  description?: string | null;
  name: string;
}
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  control_center_contract: Addr;
  deposit_denom: string;
  max_withdrawals_per_user: number;
  token_info_provider_contract?: Addr | null;
  vault_shares_denom: string;
}
export interface FundedWithdrawalRequestsResponse {
  withdrawal_ids: number[];
}
export interface AdaptersListResponse {
  adapters: [string, AdapterInfo][];
}
export interface PoolInfoResponse {
  adapter_deposits_base_tokens: Uint128;
  balance_base_tokens: Uint128;
  shares_issued: Uint128;
  withdrawal_queue_base_tokens: Uint128;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface UserPayoutsHistoryResponse {
  payouts: PayoutEntry[];
}
export interface PayoutEntry {
  amount_received: Uint128;
  executed_at: Timestamp;
  id: number;
  recipient: Addr;
  vault_shares_burned: Uint128;
}
export interface UserWithdrawalRequestsResponse {
  withdrawals: WithdrawalEntry[];
}
export interface WithdrawalEntry {
  amount_to_receive: Uint128;
  id: number;
  initiated_at: Timestamp;
  is_funded: boolean;
  shares_burned: Uint128;
  withdrawer: Addr;
}
export interface WhitelistResponse {
  whitelist: Addr[];
}
export interface WithdrawalQueueInfoResponse {
  info: WithdrawalQueueInfo;
}
export interface WithdrawalQueueInfo {
  non_funded_withdrawal_amount: Uint128;
  total_shares_burned: Uint128;
  total_withdrawal_amount: Uint128;
}