/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { InstantiateMsg, DenomMetadata, ExecuteMsg, Uint128, AllocationMode, DeploymentTracking, UpdateConfigData, QueryMsg, Order, Addr, AdapterInfoResponse, AdapterInfo, ConfigResponse, Config, FundedWithdrawalRequestsResponse, AdaptersListResponse, PoolInfoResponse, Timestamp, Uint64, UserPayoutsHistoryResponse, PayoutEntry, UserWithdrawalRequestsResponse, WithdrawalEntry, WhitelistResponse, WithdrawalQueueInfoResponse, WithdrawalQueueInfo } from "./InflowVaultBase.types";
export interface InflowVaultBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  poolInfo: () => Promise<PoolInfoResponse>;
  sharesEquivalentValue: ({
    shares
  }: {
    shares: Uint128;
  }) => Promise<Uint128>;
  userSharesEquivalentValue: ({
    address
  }: {
    address: string;
  }) => Promise<Uint128>;
  availableForDeployment: () => Promise<Uint128>;
  withdrawalQueueInfo: () => Promise<WithdrawalQueueInfoResponse>;
  amountToFundPendingWithdrawals: () => Promise<Uint128>;
  fundedWithdrawalRequests: ({
    limit
  }: {
    limit: number;
  }) => Promise<FundedWithdrawalRequestsResponse>;
  userWithdrawalRequests: ({
    address,
    limit,
    startFrom
  }: {
    address: string;
    limit: number;
    startFrom: number;
  }) => Promise<UserWithdrawalRequestsResponse>;
  userPayoutsHistory: ({
    address,
    limit,
    order,
    startFrom
  }: {
    address: string;
    limit: number;
    order: Order;
    startFrom: number;
  }) => Promise<UserPayoutsHistoryResponse>;
  whitelist: () => Promise<WhitelistResponse>;
  listAdapters: () => Promise<AdaptersListResponse>;
  adapterInfo: ({
    name
  }: {
    name: string;
  }) => Promise<AdapterInfoResponse>;
}
export class InflowVaultBaseQueryClient implements InflowVaultBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.poolInfo = this.poolInfo.bind(this);
    this.sharesEquivalentValue = this.sharesEquivalentValue.bind(this);
    this.userSharesEquivalentValue = this.userSharesEquivalentValue.bind(this);
    this.availableForDeployment = this.availableForDeployment.bind(this);
    this.withdrawalQueueInfo = this.withdrawalQueueInfo.bind(this);
    this.amountToFundPendingWithdrawals = this.amountToFundPendingWithdrawals.bind(this);
    this.fundedWithdrawalRequests = this.fundedWithdrawalRequests.bind(this);
    this.userWithdrawalRequests = this.userWithdrawalRequests.bind(this);
    this.userPayoutsHistory = this.userPayoutsHistory.bind(this);
    this.whitelist = this.whitelist.bind(this);
    this.listAdapters = this.listAdapters.bind(this);
    this.adapterInfo = this.adapterInfo.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  poolInfo = async (): Promise<PoolInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_info: {}
    });
  };
  sharesEquivalentValue = async ({
    shares
  }: {
    shares: Uint128;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      shares_equivalent_value: {
        shares
      }
    });
  };
  userSharesEquivalentValue = async ({
    address
  }: {
    address: string;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_shares_equivalent_value: {
        address
      }
    });
  };
  availableForDeployment = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_for_deployment: {}
    });
  };
  withdrawalQueueInfo = async (): Promise<WithdrawalQueueInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      withdrawal_queue_info: {}
    });
  };
  amountToFundPendingWithdrawals = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      amount_to_fund_pending_withdrawals: {}
    });
  };
  fundedWithdrawalRequests = async ({
    limit
  }: {
    limit: number;
  }): Promise<FundedWithdrawalRequestsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      funded_withdrawal_requests: {
        limit
      }
    });
  };
  userWithdrawalRequests = async ({
    address,
    limit,
    startFrom
  }: {
    address: string;
    limit: number;
    startFrom: number;
  }): Promise<UserWithdrawalRequestsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_withdrawal_requests: {
        address,
        limit,
        start_from: startFrom
      }
    });
  };
  userPayoutsHistory = async ({
    address,
    limit,
    order,
    startFrom
  }: {
    address: string;
    limit: number;
    order: Order;
    startFrom: number;
  }): Promise<UserPayoutsHistoryResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_payouts_history: {
        address,
        limit,
        order,
        start_from: startFrom
      }
    });
  };
  whitelist = async (): Promise<WhitelistResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      whitelist: {}
    });
  };
  listAdapters = async (): Promise<AdaptersListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_adapters: {}
    });
  };
  adapterInfo = async ({
    name
  }: {
    name: string;
  }): Promise<AdapterInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      adapter_info: {
        name
      }
    });
  };
}
export interface InflowVaultBaseInterface extends InflowVaultBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  deposit: ({
    onBehalfOf
  }: {
    onBehalfOf?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdraw: ({
    onBehalfOf
  }: {
    onBehalfOf?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  cancelWithdrawal: ({
    withdrawalIds
  }: {
    withdrawalIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  fulfillPendingWithdrawals: ({
    limit
  }: {
    limit: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  claimUnbondedWithdrawals: ({
    withdrawalIds
  }: {
    withdrawalIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdrawForDeployment: ({
    amount
  }: {
    amount: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  setTokenInfoProviderContract: ({
    address
  }: {
    address?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  addToWhitelist: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  removeFromWhitelist: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    config
  }: {
    config: UpdateConfigData;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerAdapter: ({
    address,
    allocationMode,
    deploymentTracking,
    description,
    name
  }: {
    address: string;
    allocationMode: AllocationMode;
    deploymentTracking: DeploymentTracking;
    description?: string;
    name: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  unregisterAdapter: ({
    name
  }: {
    name: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  setAdapterAllocationMode: ({
    allocationMode,
    name
  }: {
    allocationMode: AllocationMode;
    name: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  setAdapterDeploymentTracking: ({
    deploymentTracking,
    name
  }: {
    deploymentTracking: DeploymentTracking;
    name: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdrawFromAdapter: ({
    adapterName,
    amount
  }: {
    adapterName: string;
    amount: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  depositToAdapter: ({
    adapterName,
    amount
  }: {
    adapterName: string;
    amount: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowVaultBaseClient extends InflowVaultBaseQueryClient implements InflowVaultBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.cancelWithdrawal = this.cancelWithdrawal.bind(this);
    this.fulfillPendingWithdrawals = this.fulfillPendingWithdrawals.bind(this);
    this.claimUnbondedWithdrawals = this.claimUnbondedWithdrawals.bind(this);
    this.withdrawForDeployment = this.withdrawForDeployment.bind(this);
    this.setTokenInfoProviderContract = this.setTokenInfoProviderContract.bind(this);
    this.addToWhitelist = this.addToWhitelist.bind(this);
    this.removeFromWhitelist = this.removeFromWhitelist.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.registerAdapter = this.registerAdapter.bind(this);
    this.unregisterAdapter = this.unregisterAdapter.bind(this);
    this.setAdapterAllocationMode = this.setAdapterAllocationMode.bind(this);
    this.setAdapterDeploymentTracking = this.setAdapterDeploymentTracking.bind(this);
    this.withdrawFromAdapter = this.withdrawFromAdapter.bind(this);
    this.depositToAdapter = this.depositToAdapter.bind(this);
  }
  deposit = async ({
    onBehalfOf
  }: {
    onBehalfOf?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit: {
        on_behalf_of: onBehalfOf
      }
    }, fee_, memo_, funds_);
  };
  withdraw = async ({
    onBehalfOf
  }: {
    onBehalfOf?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        on_behalf_of: onBehalfOf
      }
    }, fee_, memo_, funds_);
  };
  cancelWithdrawal = async ({
    withdrawalIds
  }: {
    withdrawalIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_withdrawal: {
        withdrawal_ids: withdrawalIds
      }
    }, fee_, memo_, funds_);
  };
  fulfillPendingWithdrawals = async ({
    limit
  }: {
    limit: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      fulfill_pending_withdrawals: {
        limit
      }
    }, fee_, memo_, funds_);
  };
  claimUnbondedWithdrawals = async ({
    withdrawalIds
  }: {
    withdrawalIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_unbonded_withdrawals: {
        withdrawal_ids: withdrawalIds
      }
    }, fee_, memo_, funds_);
  };
  withdrawForDeployment = async ({
    amount
  }: {
    amount: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_for_deployment: {
        amount
      }
    }, fee_, memo_, funds_);
  };
  setTokenInfoProviderContract = async ({
    address
  }: {
    address?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_token_info_provider_contract: {
        address
      }
    }, fee_, memo_, funds_);
  };
  addToWhitelist = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_to_whitelist: {
        address
      }
    }, fee_, memo_, funds_);
  };
  removeFromWhitelist = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_from_whitelist: {
        address
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    config
  }: {
    config: UpdateConfigData;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        config
      }
    }, fee_, memo_, funds_);
  };
  registerAdapter = async ({
    address,
    allocationMode,
    deploymentTracking,
    description,
    name
  }: {
    address: string;
    allocationMode: AllocationMode;
    deploymentTracking: DeploymentTracking;
    description?: string;
    name: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_adapter: {
        address,
        allocation_mode: allocationMode,
        deployment_tracking: deploymentTracking,
        description,
        name
      }
    }, fee_, memo_, funds_);
  };
  unregisterAdapter = async ({
    name
  }: {
    name: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unregister_adapter: {
        name
      }
    }, fee_, memo_, funds_);
  };
  setAdapterAllocationMode = async ({
    allocationMode,
    name
  }: {
    allocationMode: AllocationMode;
    name: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_adapter_allocation_mode: {
        allocation_mode: allocationMode,
        name
      }
    }, fee_, memo_, funds_);
  };
  setAdapterDeploymentTracking = async ({
    deploymentTracking,
    name
  }: {
    deploymentTracking: DeploymentTracking;
    name: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_adapter_deployment_tracking: {
        deployment_tracking: deploymentTracking,
        name
      }
    }, fee_, memo_, funds_);
  };
  withdrawFromAdapter = async ({
    adapterName,
    amount
  }: {
    adapterName: string;
    amount: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_from_adapter: {
        adapter_name: adapterName,
        amount
      }
    }, fee_, memo_, funds_);
  };
  depositToAdapter = async ({
    adapterName,
    amount
  }: {
    adapterName: string;
    amount: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_to_adapter: {
        adapter_name: adapterName,
        amount
      }
    }, fee_, memo_, funds_);
  };
}