/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, Coin, QueryMsg, AvailableAmountResponse, AdapterConfigResponse, InflowDepositResponse, InflowDepositsResponse, RegisteredInflowsResponse, RegisteredInflowInfo, TimeEstimateResponse, TotalDepositedResponse } from "./InflowMarsAdapterBase.types";
export interface InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  availableForDeposit: ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }) => Promise<AvailableAmountResponse>;
  availableForWithdraw: ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }) => Promise<AvailableAmountResponse>;
  timeToWithdraw: ({
    coin,
    inflowAddress
  }: {
    coin: Coin;
    inflowAddress: string;
  }) => Promise<TimeEstimateResponse>;
  config: () => Promise<AdapterConfigResponse>;
  totalDeposited: () => Promise<TotalDepositedResponse>;
  registeredInflows: ({
    enabled
  }: {
    enabled?: boolean;
  }) => Promise<RegisteredInflowsResponse>;
  inflowDeposit: ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }) => Promise<InflowDepositResponse>;
  inflowDeposits: ({
    inflowAddress
  }: {
    inflowAddress: string;
  }) => Promise<InflowDepositsResponse>;
}
export class InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.availableForDeposit = this.availableForDeposit.bind(this);
    this.availableForWithdraw = this.availableForWithdraw.bind(this);
    this.timeToWithdraw = this.timeToWithdraw.bind(this);
    this.config = this.config.bind(this);
    this.totalDeposited = this.totalDeposited.bind(this);
    this.registeredInflows = this.registeredInflows.bind(this);
    this.inflowDeposit = this.inflowDeposit.bind(this);
    this.inflowDeposits = this.inflowDeposits.bind(this);
  }
  availableForDeposit = async ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }): Promise<AvailableAmountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_for_deposit: {
        denom,
        inflow_address: inflowAddress
      }
    });
  };
  availableForWithdraw = async ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }): Promise<AvailableAmountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_for_withdraw: {
        denom,
        inflow_address: inflowAddress
      }
    });
  };
  timeToWithdraw = async ({
    coin,
    inflowAddress
  }: {
    coin: Coin;
    inflowAddress: string;
  }): Promise<TimeEstimateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      time_to_withdraw: {
        coin,
        inflow_address: inflowAddress
      }
    });
  };
  config = async (): Promise<AdapterConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  totalDeposited = async (): Promise<TotalDepositedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_deposited: {}
    });
  };
  registeredInflows = async ({
    enabled
  }: {
    enabled?: boolean;
  }): Promise<RegisteredInflowsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      registered_inflows: {
        enabled
      }
    });
  };
  inflowDeposit = async ({
    denom,
    inflowAddress
  }: {
    denom: string;
    inflowAddress: string;
  }): Promise<InflowDepositResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      inflow_deposit: {
        denom,
        inflow_address: inflowAddress
      }
    });
  };
  inflowDeposits = async ({
    inflowAddress
  }: {
    inflowAddress: string;
  }): Promise<InflowDepositsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      inflow_deposits: {
        inflow_address: inflowAddress
      }
    });
  };
}
export interface InflowMarsAdapterBaseInterface extends InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  deposit: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdraw: ({
    coin
  }: {
    coin: Coin;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerInflow: ({
    inflowAddress
  }: {
    inflowAddress: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  unregisterInflow: ({
    inflowAddress
  }: {
    inflowAddress: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  toggleInflowEnabled: ({
    enabled,
    inflowAddress
  }: {
    enabled: boolean;
    inflowAddress: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    protocolAddress,
    supportedDenoms
  }: {
    protocolAddress?: string;
    supportedDenoms?: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowMarsAdapterBaseClient extends InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.registerInflow = this.registerInflow.bind(this);
    this.unregisterInflow = this.unregisterInflow.bind(this);
    this.toggleInflowEnabled = this.toggleInflowEnabled.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
  }
  deposit = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit: {}
    }, fee_, memo_, funds_);
  };
  withdraw = async ({
    coin
  }: {
    coin: Coin;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        coin
      }
    }, fee_, memo_, funds_);
  };
  registerInflow = async ({
    inflowAddress
  }: {
    inflowAddress: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_inflow: {
        inflow_address: inflowAddress
      }
    }, fee_, memo_, funds_);
  };
  unregisterInflow = async ({
    inflowAddress
  }: {
    inflowAddress: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unregister_inflow: {
        inflow_address: inflowAddress
      }
    }, fee_, memo_, funds_);
  };
  toggleInflowEnabled = async ({
    enabled,
    inflowAddress
  }: {
    enabled: boolean;
    inflowAddress: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      toggle_inflow_enabled: {
        enabled,
        inflow_address: inflowAddress
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    protocolAddress,
    supportedDenoms
  }: {
    protocolAddress?: string;
    supportedDenoms?: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        protocol_address: protocolAddress,
        supported_denoms: supportedDenoms
      }
    }, fee_, memo_, funds_);
  };
}