/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  denom: string;
  ibc_default_timeout_seconds: number;
  initial_chains: InitialChainConfig[];
  initial_depositors: InitialDepositor[];
  initial_executors: InitialExecutor[];
  noble_transfer_channel_id: string;
}
export interface InitialChainConfig {
  chain_config: ChainConfig;
  initial_allowed_destination_addresses: DestinationAddress[];
}
export interface ChainConfig {
  bridging_config: BridgingConfig;
  chain_id: string;
}
export interface BridgingConfig {
  destination_domain: number;
  evm_destination_caller: string;
  noble_fee_recipient: string;
  noble_receiver: string;
}
export interface DestinationAddress {
  address: string;
  protocol: string;
}
export interface InitialDepositor {
  address: string;
  capabilities?: DepositorCapabilities | null;
}
export interface DepositorCapabilities {
  can_withdraw: boolean;
}
export interface InitialExecutor {
  address: string;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: CctpAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
};
export type Uint128 = string;
export type Binary = string;
export type CctpAdapterMsg = {
  update_config: {
    update: UpdateConfigData;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  add_admin: {
    admin_address: string;
  };
} | {
  remove_admin: {
    admin_address: string;
  };
} | {
  register_chain: {
    chain_config: ChainConfig;
  };
} | {
  update_registered_chain: {
    chain_config: ChainConfig;
  };
} | {
  unregister_chain: {
    chain_id: string;
  };
} | {
  add_allowed_destination_address: {
    address: string;
    chain_id: string;
    protocol: string;
  };
} | {
  remove_allowed_destination_address: {
    address: string;
    chain_id: string;
  };
} | {
  transfer_funds: {
    amount: Uint128;
    instructions: TransferFundsInstructions;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface UpdateConfigData {
  denom?: string | null;
  ibc_default_timeout_seconds?: number | null;
  noble_transfer_channel_id?: string | null;
}
export interface TransferFundsInstructions {
  chain_id: string;
  recipient: string;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: CctpAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export type CctpAdapterQueryMsg = {
  chain_config: {
    chain_id: string;
  };
} | {
  all_chains: {};
} | {
  executors: {};
} | {
  admins: {};
} | {
  depositor_capabilities: {
    depositor_address: string;
  };
} | {
  allowed_destination_addresses: {
    chain_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
};