/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin: string;
  pairs: ConversionPair[];
}
export interface ConversionPair {
  cosmos_hub_shares_denom: string;
  neutron_shares_denom: string;
}
export type ExecuteMsg = {
  convert: {};
} | {
  add_pair: {
    cosmos_hub_shares_denom: string;
    neutron_shares_denom: string;
  };
} | {
  remove_pair: {
    neutron_shares_denom: string;
  };
} | {
  update_admin: {
    new_admin: string;
  };
};
export type QueryMsg = {
  config: {};
} | {
  pair: {
    neutron_denom: string;
  };
} | {
  all_pairs: {
    limit?: number | null;
    start_after?: string | null;
  };
};
export interface AllPairsResponse {
  pairs: PairResponse[];
}
export interface PairResponse {
  cosmos_hub_shares_denom: string;
  neutron_shares_denom: string;
}
export interface ConfigResponse {
  admin: string;
}
export type NullablePairResponse = PairResponse | null;