/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admins: string[];
  ibc_default_timeout_seconds: number;
  initial_chains: InitialChainConfig[];
  initial_depositors: InitialDepositor[];
  initial_executors: InitialExecutor[];
  initial_recover_addresses: string[];
  initial_tokens: TokenConfig[];
  neutron_to_hub_channel: string;
  skip_entry_point: string;
  skip_ibc_adapter: string;
}
export interface InitialChainConfig {
  chain_config: ChainConfig;
  initial_allowed_destination_addresses: string[];
}
export interface ChainConfig {
  chain_id: string;
  eureka_fee_receiver: string;
  eureka_source_channel: string;
  max_eureka_fee: Uint128;
  min_eureka_fee: Uint128;
}
export interface InitialDepositor {
  address: string;
  capabilities?: DepositorCapabilities | null;
}
export interface DepositorCapabilities {
  can_withdraw: boolean;
}
export interface InitialExecutor {
  address: string;
}
export interface TokenConfig {
  denom: string;
  hub_denom: string;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: EurekaAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
} | {
  add_admin: {
    admin_address: string;
  };
} | {
  remove_admin: {
    admin_address: string;
  };
};
export type Binary = string;
export type EurekaAdapterMsg = {
  transfer_funds: {
    instructions: TransferFundsInstructions;
  };
} | {
  update_config: {
    update: UpdateConfigData;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  register_chain: {
    chain_config: ChainConfig;
  };
} | {
  update_registered_chain: {
    chain_config: ChainConfig;
  };
} | {
  unregister_chain: {
    chain_id: string;
  };
} | {
  register_token: {
    denom: string;
    hub_denom: string;
  };
} | {
  unregister_token: {
    denom: string;
  };
} | {
  add_allowed_destination_address: {
    address: string;
    chain_id: string;
  };
} | {
  remove_allowed_destination_address: {
    address: string;
    chain_id: string;
  };
} | {
  add_allowed_recover_address: {
    address: string;
  };
} | {
  remove_allowed_recover_address: {
    address: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface TransferFundsInstructions {
  amount: Uint128;
  chain_id: string;
  denom: string;
  recipient: string;
  recover_address: string;
}
export interface UpdateConfigData {
  ibc_default_timeout_seconds?: number | null;
  neutron_to_hub_channel?: string | null;
  skip_entry_point?: string | null;
  skip_ibc_adapter?: string | null;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: EurekaAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
} | {
  admins: {};
};
export type EurekaAdapterQueryMsg = {
  config: {};
} | {
  chain_config: {
    chain_id: string;
  };
} | {
  all_chains: {};
} | {
  token_config: {
    denom: string;
  };
} | {
  all_tokens: {};
} | {
  executors: {};
} | {
  depositor_capabilities: {
    depositor_address: string;
  };
} | {
  allowed_destination_addresses: {
    chain_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  allowed_recover_addresses: {
    limit?: number | null;
    start_after?: string | null;
  };
};