/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, QueryMsg, Addr, ActionState, StateResponse, State } from "./InflowProxyBase.types";
export interface InflowProxyBaseReadOnlyInterface {
  contractAddress: string;
  state: () => Promise<StateResponse>;
}
export class InflowProxyBaseQueryClient implements InflowProxyBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.state = this.state.bind(this);
  }
  state = async (): Promise<StateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      state: {}
    });
  };
}
export interface InflowProxyBaseInterface extends InflowProxyBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  forwardToInflow: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawReceiptTokens: ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawFunds: ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class InflowProxyBaseClient extends InflowProxyBaseQueryClient implements InflowProxyBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.forwardToInflow = this.forwardToInflow.bind(this);
    this.withdrawReceiptTokens = this.withdrawReceiptTokens.bind(this);
    this.withdrawFunds = this.withdrawFunds.bind(this);
  }
  forwardToInflow = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      forward_to_inflow: {}
    }, fee, memo, _funds);
  };
  withdrawReceiptTokens = async ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_receipt_tokens: {
        address,
        amount
      }
    }, fee, memo, _funds);
  };
  withdrawFunds = async ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_funds: {
        address,
        amount
      }
    }, fee, memo, _funds);
  };
}