/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, Coin, QueryMsg, Addr, ConfigResponse, Config } from "./InflowProxyBase.types";
export interface InflowProxyBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
}
export class InflowProxyBaseQueryClient implements InflowProxyBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
}
export interface InflowProxyBaseInterface extends InflowProxyBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  forwardToInflow: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawReceiptTokens: ({
    address,
    coin
  }: {
    address: string;
    coin: Coin;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawFunds: ({
    address,
    coin
  }: {
    address: string;
    coin: Coin;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class InflowProxyBaseClient extends InflowProxyBaseQueryClient implements InflowProxyBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.forwardToInflow = this.forwardToInflow.bind(this);
    this.withdrawReceiptTokens = this.withdrawReceiptTokens.bind(this);
    this.withdrawFunds = this.withdrawFunds.bind(this);
  }
  forwardToInflow = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      forward_to_inflow: {}
    }, fee, memo, _funds);
  };
  withdrawReceiptTokens = async ({
    address,
    coin
  }: {
    address: string;
    coin: Coin;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_receipt_tokens: {
        address,
        coin
      }
    }, fee, memo, _funds);
  };
  withdrawFunds = async ({
    address,
    coin
  }: {
    address: string;
    coin: Coin;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_funds: {
        address,
        coin
      }
    }, fee, memo, _funds);
  };
}