/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  inflow_address?: string | null;
  mars_contract: string;
  supported_denoms: string[];
}
export type ExecuteMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_inflow: {
    inflow_address: string;
  };
} | {
  unregister_inflow: {
    inflow_address: string;
  };
} | {
  toggle_inflow_enabled: {
    enabled: boolean;
    inflow_address: string;
  };
} | {
  update_config: {
    protocol_address?: string | null;
    supported_denoms?: string[] | null;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type QueryMsg = {
  available_for_deposit: {
    denom: string;
    inflow_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    inflow_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    inflow_address: string;
  };
} | {
  config: {};
} | {
  total_deposited: {};
} | {
  registered_inflows: {
    enabled?: boolean | null;
  };
} | {
  inflow_deposit: {
    denom: string;
    inflow_address: string;
  };
} | {
  inflow_deposits: {
    inflow_address: string;
  };
};
export interface AvailableAmountResponse {
  amount: Uint128;
}
export interface AdapterConfigResponse {
  protocol_address: string;
  supported_denoms: string[];
}
export interface InflowDepositResponse {
  amount: Uint128;
}
export interface InflowDepositsResponse {
  deposits: Coin[];
}
export interface RegisteredInflowsResponse {
  inflows: RegisteredInflowInfo[];
}
export interface RegisteredInflowInfo {
  enabled: boolean;
  inflow_address: string;
}
export interface TimeEstimateResponse {
  blocks: number;
  seconds: number;
}
export interface TotalDepositedResponse {
  deposits: Coin[];
}