/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, AdapterInterfaceMsg, Uint128, Binary, MarsAdapterMsg, Coin, QueryMsg, AdapterInterfaceQueryMsg, MarsAdapterQueryMsg } from "./InflowMarsAdapterBase.types";
export interface InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  standardQuery: (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg) => Promise<Binary>;
  customQuery: () => Promise<Binary>;
}
export class InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.standardQuery = this.standardQuery.bind(this);
    this.customQuery = this.customQuery.bind(this);
  }
  standardQuery = async (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      standard_query: adapterInterfaceQueryMsg
    });
  };
  customQuery = async (): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      custom_query: {}
    });
  };
}
export interface InflowMarsAdapterBaseInterface extends InflowMarsAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  standardAction: (adapterInterfaceMsg: AdapterInterfaceMsg, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  customAction: (marsAdapterMsg: MarsAdapterMsg, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowMarsAdapterBaseClient extends InflowMarsAdapterBaseQueryClient implements InflowMarsAdapterBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.standardAction = this.standardAction.bind(this);
    this.customAction = this.customAction.bind(this);
  }
  standardAction = async (adapterInterfaceMsg: AdapterInterfaceMsg, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      standard_action: adapterInterfaceMsg
    }, fee_, memo_, funds_);
  };
  customAction = async (marsAdapterMsg: MarsAdapterMsg, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      custom_action: marsAdapterMsg
    }, fee_, memo_, funds_);
  };
}