/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  admins: string[];
  default_timeout_seconds: number;
  initial_chains: ChainConfig[];
  initial_depositors: InitialDepositor[];
  initial_executors: string[];
  initial_tokens: TokenConfig[];
}
export interface ChainConfig {
  allowed_recipients: string[];
  chain_id: string;
  channel_from_neutron: string;
}
export interface InitialDepositor {
  address: string;
  capabilities?: Binary | null;
}
export interface TokenConfig {
  denom: string;
  source_chain_id: string;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: IbcAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
};
export type Uint128 = string;
export type IbcAdapterMsg = {
  transfer_funds: {
    coin: Coin;
    instructions: TransferFundsInstructions;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  register_chain: {
    allowed_recipients: string[];
    chain_id: string;
    channel_from_neutron: string;
  };
} | {
  unregister_chain: {
    chain_id: string;
  };
} | {
  register_token: {
    denom: string;
    source_chain_id: string;
  };
} | {
  unregister_token: {
    denom: string;
  };
} | {
  update_config: {
    default_timeout_seconds: number;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface TransferFundsInstructions {
  destination_chain: string;
  memo?: string | null;
  recipient: string;
  timeout_seconds?: number | null;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: IbcAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export type IbcAdapterQueryMsg = {
  chain_config: {
    chain_id: string;
  };
} | {
  all_chains: {};
} | {
  token_config: {
    denom: string;
  };
} | {
  all_tokens: {};
} | {
  executors: {};
} | {
  depositor_capabilities: {
    depositor_address: string;
  };
};