/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  deposit_denom: string;
  subdenom: string;
  token_metadata: DenomMetadata;
  whitelist: string[];
}
export interface DenomMetadata {
  description: string;
  display: string;
  exponent: number;
  name: string;
  symbol: string;
  uri?: string | null;
  uri_hash?: string | null;
}
export type ExecuteMsg = {
  deposit: {};
} | {
  submit_deployed_amount: {
    amount: Uint128;
  };
} | {
  withdraw_for_deployment: {
    amount: Uint128;
  };
} | {
  add_to_whitelist: {
    address: string;
  };
} | {
  remove_from_whitelist: {
    address: string;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  config: {};
} | {
  total_shares_issued: {};
} | {
  total_pool_value: {};
} | {
  shares_equivalent_value: {
    shares: Uint128;
  };
} | {
  user_shares_equivalent_value: {
    address: string;
  };
} | {
  deployed_amount: {};
};
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  deposit_denom: string;
}