/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { Uint128, InstantiateMsg, ExecuteMsg, DeploymentDirection, UpdateConfigData, QueryMsg, ConfigResponse, Config, PoolInfoResponse, Addr, SubvaultsResponse, WhitelistResponse } from "./InflowControlCenterBase.types";
export interface InflowControlCenterBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  deployedAmount: () => Promise<Uint128>;
  poolInfo: () => Promise<PoolInfoResponse>;
  whitelist: () => Promise<WhitelistResponse>;
  subvaults: () => Promise<SubvaultsResponse>;
}
export class InflowControlCenterBaseQueryClient implements InflowControlCenterBaseReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.deployedAmount = this.deployedAmount.bind(this);
    this.poolInfo = this.poolInfo.bind(this);
    this.whitelist = this.whitelist.bind(this);
    this.subvaults = this.subvaults.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  deployedAmount = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      deployed_amount: {}
    });
  };
  poolInfo = async (): Promise<PoolInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_info: {}
    });
  };
  whitelist = async (): Promise<WhitelistResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      whitelist: {}
    });
  };
  subvaults = async (): Promise<SubvaultsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      subvaults: {}
    });
  };
}
export interface InflowControlCenterBaseInterface extends InflowControlCenterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  submitDeployedAmount: ({
    amount
  }: {
    amount: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateDeployedAmount: ({
    amount,
    direction
  }: {
    amount: Uint128;
    direction: DeploymentDirection;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  addToWhitelist: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  removeFromWhitelist: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    config
  }: {
    config: UpdateConfigData;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  addSubvault: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  removeSubvault: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class InflowControlCenterBaseClient extends InflowControlCenterBaseQueryClient implements InflowControlCenterBaseInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.submitDeployedAmount = this.submitDeployedAmount.bind(this);
    this.updateDeployedAmount = this.updateDeployedAmount.bind(this);
    this.addToWhitelist = this.addToWhitelist.bind(this);
    this.removeFromWhitelist = this.removeFromWhitelist.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.addSubvault = this.addSubvault.bind(this);
    this.removeSubvault = this.removeSubvault.bind(this);
  }
  submitDeployedAmount = async ({
    amount
  }: {
    amount: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      submit_deployed_amount: {
        amount
      }
    }, fee_, memo_, funds_);
  };
  updateDeployedAmount = async ({
    amount,
    direction
  }: {
    amount: Uint128;
    direction: DeploymentDirection;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_deployed_amount: {
        amount,
        direction
      }
    }, fee_, memo_, funds_);
  };
  addToWhitelist = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_to_whitelist: {
        address
      }
    }, fee_, memo_, funds_);
  };
  removeFromWhitelist = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_from_whitelist: {
        address
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    config
  }: {
    config: UpdateConfigData;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        config
      }
    }, fee_, memo_, funds_);
  };
  addSubvault = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_subvault: {
        address
      }
    }, fee_, memo_, funds_);
  };
  removeSubvault = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_subvault: {
        address
      }
    }, fee_, memo_, funds_);
  };
}