/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { InstantiateMsg, TokenRegistration, ExecuteMsg, AdapterInterfaceMsg, Uint128, Binary, DAssetAdapterMsg, Coin, QueryMsg, AdapterInterfaceQueryMsg, DAssetAdapterQueryMsg } from "./InflowDAssetAdapterBase.types";
export interface InflowDAssetAdapterBaseReadOnlyInterface {
  contractAddress: string;
  standardQuery: (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg) => Promise<Binary>;
  customQuery: (dAssetAdapterQueryMsg: DAssetAdapterQueryMsg) => Promise<Binary>;
}
export class InflowDAssetAdapterBaseQueryClient implements InflowDAssetAdapterBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.standardQuery = this.standardQuery.bind(this);
    this.customQuery = this.customQuery.bind(this);
  }
  standardQuery = async (adapterInterfaceQueryMsg: AdapterInterfaceQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      standard_query: adapterInterfaceQueryMsg
    });
  };
  customQuery = async (dAssetAdapterQueryMsg: DAssetAdapterQueryMsg): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      custom_query: dAssetAdapterQueryMsg
    });
  };
}
export interface InflowDAssetAdapterBaseInterface extends InflowDAssetAdapterBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  standardAction: (adapterInterfaceMsg: AdapterInterfaceMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  customAction: (dAssetAdapterMsg: DAssetAdapterMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class InflowDAssetAdapterBaseClient extends InflowDAssetAdapterBaseQueryClient implements InflowDAssetAdapterBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.standardAction = this.standardAction.bind(this);
    this.customAction = this.customAction.bind(this);
  }
  standardAction = async (adapterInterfaceMsg: AdapterInterfaceMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      standard_action: adapterInterfaceMsg
    }, fee, memo, _funds);
  };
  customAction = async (dAssetAdapterMsg: DAssetAdapterMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      custom_action: dAssetAdapterMsg
    }, fee, memo, _funds);
  };
}