/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  default_timeout_nanos: number;
  depositor_address?: string | null;
  executors?: string[] | null;
  initial_recipients?: [string, RecipientConfig][] | null;
  initial_routes?: [string, RouteConfig][] | null;
  skip_contract: string;
}
export interface RecipientConfig {
  address: string;
  description?: string | null;
  enabled: boolean;
}
export interface RouteConfig {
  denom_in: string;
  denom_out: string;
  denoms_path: string[];
  enabled: boolean;
}
export type ExecuteMsg = {
  standard_action: AdapterInterfaceMsg;
} | {
  custom_action: SkipAdapterMsg;
};
export type AdapterInterfaceMsg = {
  deposit: {};
} | {
  withdraw: {
    coin: Coin;
  };
} | {
  register_depositor: {
    depositor_address: string;
    metadata?: Binary | null;
  };
} | {
  unregister_depositor: {
    depositor_address: string;
  };
} | {
  set_depositor_enabled: {
    depositor_address: string;
    enabled: boolean;
  };
};
export type Uint128 = string;
export type Binary = string;
export type SkipAdapterMsg = {
  execute_swap: {
    params: SwapExecutionParams;
  };
} | {
  add_executor: {
    executor_address: string;
  };
} | {
  remove_executor: {
    executor_address: string;
  };
} | {
  register_route: {
    route_config: RouteConfig;
    route_id: string;
  };
} | {
  unregister_route: {
    route_id: string;
  };
} | {
  set_route_enabled: {
    enabled: boolean;
    route_id: string;
  };
} | {
  register_recipient: {
    description?: string | null;
    recipient_address: string;
  };
} | {
  unregister_recipient: {
    recipient_address: string;
  };
} | {
  set_recipient_enabled: {
    enabled: boolean;
    recipient_address: string;
  };
} | {
  update_config: {
    default_timeout_nanos?: number | null;
    skip_contract?: string | null;
  };
};
export type Asset = {
  native: {
    amount: Uint128;
    denom: string;
  };
} | {
  cw20: {
    address: string;
    amount: Uint128;
  };
};
export type PostSwapAction = {
  transfer: {
    to_address: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface SwapExecutionParams {
  coin_in: Coin;
  min_asset: Asset;
  operations: SwapOperation[];
  post_swap_action?: PostSwapAction | null;
  route_id: string;
  swap_venue_name: string;
  timeout_nanos?: number | null;
}
export interface SwapOperation {
  denom_in: string;
  denom_out: string;
  interface?: Binary | null;
  pool: string;
}
export type QueryMsg = {
  standard_query: AdapterInterfaceQueryMsg;
} | {
  custom_query: SkipAdapterQueryMsg;
};
export type AdapterInterfaceQueryMsg = {
  available_for_deposit: {
    denom: string;
    depositor_address: string;
  };
} | {
  available_for_withdraw: {
    denom: string;
    depositor_address: string;
  };
} | {
  time_to_withdraw: {
    coin: Coin;
    depositor_address: string;
  };
} | {
  config: {};
} | {
  all_positions: {};
} | {
  registered_depositors: {
    enabled?: boolean | null;
  };
} | {
  depositor_position: {
    denom: string;
    depositor_address: string;
  };
} | {
  depositor_positions: {
    depositor_address: string;
  };
};
export type SkipAdapterQueryMsg = {
  config: {};
} | {
  route_config: {
    route_id: string;
  };
} | {
  all_routes: {};
} | {
  recipient_config: {
    recipient_address: string;
  };
} | {
  all_recipients: {};
} | {
  executors: {};
};