/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, AdminsResponse, ConfigResponse, Config, ValidatorsInfoResponse } from "./LSMHubTokenInfoProviderBase.types";
export interface LSMHubTokenInfoProviderBaseReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  admins: () => Promise<AdminsResponse>;
  validatorsInfo: ({
    roundId
  }: {
    roundId: number;
  }) => Promise<ValidatorsInfoResponse>;
}
export class LSMHubTokenInfoProviderBaseQueryClient implements LSMHubTokenInfoProviderBaseReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.admins = this.admins.bind(this);
    this.validatorsInfo = this.validatorsInfo.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  admins = async (): Promise<AdminsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admins: {}
    });
  };
  validatorsInfo = async ({
    roundId
  }: {
    roundId: number;
  }): Promise<ValidatorsInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      validators_info: {
        round_id: roundId
      }
    });
  };
}
export interface LSMHubTokenInfoProviderBaseInterface extends LSMHubTokenInfoProviderBaseReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateValidatorsRatios: ({
    validators
  }: {
    validators: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class LSMHubTokenInfoProviderBaseClient extends LSMHubTokenInfoProviderBaseQueryClient implements LSMHubTokenInfoProviderBaseInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateValidatorsRatios = this.updateValidatorsRatios.bind(this);
  }
  updateValidatorsRatios = async ({
    validators
  }: {
    validators: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_validators_ratios: {
        validators
      }
    }, fee, memo, _funds);
  };
}