/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  hydro_contract_address?: string | null;
  max_validator_shares_participating: number;
}
export type ExecuteMsg = {
  update_validators_ratios: {
    validators: string[];
  };
};
export type QueryMsg = {
  config: {};
} | {
  admins: {};
} | {
  validators_info: {
    round_id: number;
  };
};
export type Addr = string;
export interface AdminsResponse {
  admins: Addr[];
}
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  hydro_contract_address: Addr;
  max_validator_shares_participating: number;
}
export interface ValidatorsInfoResponse {
  round_id: number;
  validators: {};
}