/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  st_token_denom: string;
  token_group_id: string;
}
export type ExecuteMsg = string;
export type QueryMsg = {
  config: {};
} | {
  denom_info: {
    round_id: number;
  };
};
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  hydro_contract_address: Addr;
  st_token_denom: string;
  token_group_id: string;
}
export type Decimal = string;
export interface DenomInfoResponse {
  denom: string;
  ratio: Decimal;
  token_group_id: string;
}