/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  icq_update_period: number;
  st_token_denom: string;
  stride_connection_id: string;
  stride_host_zone_id: string;
  token_group_id: string;
}
export type ExecuteMsg = {
  register_host_zone_icq: {};
} | {
  remove_host_zone_icq: {};
};
export type QueryMsg = {
  config: {};
} | {
  interchain_query_info: {};
} | {
  denom_info: {
    round_id: number;
  };
} | {
  ratio_to_base_token: {
    denom: string;
  };
};
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  hydro_contract_address: Addr;
  icq_update_period: number;
  st_token_denom: string;
  stride_connection_id: string;
  stride_host_zone_id: string;
  token_group_id: string;
}
export type Decimal = string;
export interface DenomInfoResponse {
  denom: string;
  ratio: Decimal;
  token_group_id: string;
}
export type Uint128 = string;
export interface InterchainQueryInfoResponse {
  info?: InterchainQueryInfo | null;
}
export interface InterchainQueryInfo {
  creator: string;
  deposit_paid: Coin[];
  query_id: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}