/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  add_tribute: {
    proposal_id: number;
    tranche_id: number;
    [k: string]: unknown;
  };
} | {
  claim_tribute: {
    round_id: number;
    tranche_id: number;
    tribute_id: number;
    voter_address: string;
    [k: string]: unknown;
  };
} | {
  refund_tribute: {
    proposal_id: number;
    round_id: number;
    tranche_id: number;
    tribute_id: number;
    [k: string]: unknown;
  };
};
export interface InstantiateMsg {
  hydro_contract: string;
  top_n_props_count: number;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  proposal_tributes: {
    limit: number;
    proposal_id: number;
    round_id: number;
    start_from: number;
    tranche_id: number;
    [k: string]: unknown;
  };
};