/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  derivative_token_denom: string;
  hydro_contract_address?: string | null;
  initial_whitelist: string[];
  max_ratio_diff: Decimal;
  token_group_id: string;
}
export type ExecuteMsg = {
  submit_token_ratio: {
    ratio: Decimal;
  };
} | {
  add_to_whitelist: {
    address: string;
  };
} | {
  remove_from_whitelist: {
    address: string;
  };
};
export type QueryMsg = {
  config: {};
} | {
  whitelist: {};
} | {
  denom_info: {
    round_id: number;
  };
};
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  derivative_token_denom: string;
  first_submission: boolean;
  hydro_contract_address: Addr;
  max_ratio_diff: Decimal;
  token_group_id: string;
}
export interface DenomInfoResponse {
  denom: string;
  ratio: Decimal;
  token_group_id: string;
}
export interface WhitelistResponse {
  addresses: string[];
}