name: Deploy latest contracts on Neutron testnet

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy-latest-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download Neutron chain binary
        run: |
          curl -L -o neutrond https://github.com/neutron-org/neutron/releases/download/v5.0.2/neutrond-linux-amd64
          chmod +x neutrond
      
      - name: Checkout Neutron ICQ relayer repository
        uses: actions/checkout@v4
        with:
          repository: neutron-org/neutron-query-relayer
          path: ./neutron-query-relayer  # directory to checkout the repo into

      - name: Deploy latest contracts
        env:
          TESTNET_MNEMONIC: ${{ secrets.E2E_TESTS_MNEMONIC }}
        run: |
          CONFIG_FILE="./tools/deployment/config_testnet.json"

          TX_SENDER_WALLET=$(jq -r '.tx_sender_wallet' $CONFIG_FILE)
          echo $TESTNET_MNEMONIC | ./neutrond keys add $TX_SENDER_WALLET --keyring-backend test --recover

          chmod +x ./tools/deployment/setup.sh
          bash ./tools/deployment/setup.sh $CONFIG_FILE
      
      - name: Run ICQs setup script
        run: |
          echo $HYDRO_CONTRACT_ADDRESS