name: Populate Staging Contracts

on:
  push:
    branches: ["dusan/populate-staging-contracts-hub"]
  schedule:
    # run every day at 10:05 AM UTC (new round starts at 10 AM UTC time)
    - cron: '5 10 * * *'

jobs:
  populate-new-round:
    runs-on: ubuntu-latest
    steps:
      # Checkout Hydro repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Download specific gaiad binary and add it to the PATH so it can be used by other scripts
      - name: Download Cosmos Hub chain binary
        run: |
          curl -L -o gaiad https://github.com/cosmos/gaia/releases/download/v27.6.0/gaiad-v27.6.0-linux-amd64
          chmod +x gaiad
          echo "$(pwd)" >> $GITHUB_PATH
      
      # Use mnemonic to restore the wallet that will be used in next steps.
      # Set Hydro and Tribute Staging contracts addresses as env variables so they can be used by other scripts.
      - name: Setup
        env:
          # The address derived from this mnemonic (cosmos1tn7mu7wqwtt46ry3k735dxhh8s5ew4s4d35hra)
          # is in the whitelist_admins and whitelist of the Staging Hydro contract, which means it can
          # submit proposals and enter liquidity deployments information.
          WALLET_MNEMONIC: ${{ secrets.HYDRO_STAGING_MNEMONIC }}
        run: |
          CONFIG_FILE="./tools/deployment/config_mainnet_gaia.json"
          TX_SENDER_WALLET=$(jq -r '.tx_sender_wallet' $CONFIG_FILE)

          echo $WALLET_MNEMONIC | gaiad keys add $TX_SENDER_WALLET --keyring-backend test --recover

          echo "HYDRO_ATOM_CONTRACT_ADDRESS=cosmos1crzwz0uzqal7h3ev7a00cjp5nkkgeurlfywrgfgs03zyav5xmteq2d0uqk" >> $GITHUB_ENV
          echo "TRIBUTE_ATOM_CONTRACT_ADDRESS=cosmos17ryrjncgq8rrmxy0x8wrq0pcessp28xna4pw5sv506mfg3fhwj4qn89chn" >> $GITHUB_ENV
          echo "HYDRO_ATOM_TRANCHES_NUM=2" >> $GITHUB_ENV
      
      # Enter liquidity deployments info for all proposals from the previous round.
      # If the proposal power was > 0, liquidity deployment info will be entered with deployed_funds > 0.
      - name: Enter liquidity deployments for previous round
        run: |
          CONFIG_FILE="./tools/deployment/config_mainnet_gaia.json"

          chmod +x ./tools/deployment/enter_staging_liquidity_deployments.sh
          chmod +x ./tools/deployment/add_liquidity_deployments.sh

          source ./tools/deployment/enter_staging_liquidity_deployments.sh $CONFIG_FILE $HYDRO_ATOM_CONTRACT_ADDRESS $HYDRO_ATOM_TRANCHES_NUM
      
      # Run the script to create proposals with tributes in current round
      - name: Populate round with proposals and tributes
        run: |
          CONFIG_FILE="./tools/deployment/config_mainnet_gaia.json"

          chmod +x ./tools/deployment/populate_contracts.sh
          source ./tools/deployment/populate_contracts.sh $CONFIG_FILE $HYDRO_ATOM_CONTRACT_ADDRESS $TRIBUTE_ATOM_CONTRACT_ADDRESS $HYDRO_ATOM_TRANCHES_NUM
      
      # Refresh some expired lockup or create a new one, and then vote with it in all tranches of the current round
      - name: Lock tokens and vote
        run: |
          CONFIG_FILE="./tools/deployment/config_mainnet_gaia.json"

          chmod +x ./tools/deployment/lock_and_vote.sh

          TOKEN_TO_LOCK="ibc/B05539B66B72E2739B986B86391E5D08F12B8D5D2C2A7F8F8CF9ADF674DFA231"
          source ./tools/deployment/lock_and_vote.sh $CONFIG_FILE $HYDRO_ATOM_CONTRACT_ADDRESS $HYDRO_ATOM_TRANCHES_NUM $TOKEN_TO_LOCK
