name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: fmt --all -- --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --no-fail-fast
