name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --all --all-targets -- -D warnings
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unit tests
      run: cargo test --workspace --exclude test-e2e --verbose --no-fail-fast
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: E2E tests
      run: 'cargo test e2e --verbose --no-fail-fast -- "mnemonic: [SET_PRIVATE_MNEMONIC]"'
