name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: make clippy
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make compile-rust-optimizer
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unit tests
      run: make test-unit
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: E2E tests
      run: make test-e2e
      env:
        PRIVATE_MNEMONIC: "[SET_PRIVATE_MNEMONIC]"
