name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
      - artifacts/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
      - artifacts/**

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fmt
      run: make fmt-check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: make clippy
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        WORK_DIR: ${{ github.workspace }}
      run: make compile-inner
