name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/tests.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
      - artifacts/**
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - packages/interface/**
      - test/e2e/**
      - artifacts/**

env:
  CARGO_TERM_COLOR: always

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Unit tests
      run: make test-unit
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: E2E tests
      env:
        E2E_TESTS_MNEMONIC: ${{ secrets.E2E_TESTS_MNEMONIC }}
      run: make test-e2e