name: Tests

on:
  push:
    branches: [ "main", "release/**",  ]
    paths:
      - .github/workflows/tests.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - artifacts/**
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - Cargo.toml
      - Cargo.lock
      - contracts/**
      - artifacts/**

env:
  CARGO_TERM_COLOR: always

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Unit tests
      run: make test-unit
